import Head from 'next/head'
import Link from 'next/link'
import Search from '../components/search/index'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (<div>
        <Head>
            <title> rateyourdorm </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <section className={styles.hero}>
                <div className={styles.width}>
                    <div className={styles.homeNav}>
                        <Link href={`/`}><a> RateYourDorm </a></Link>
                        <Link href={`/signup`}><a>Log In</a></Link>
                    </div>
                    <div className={styles.heroContent}>
                        <h1> Rate Your Dorm </h1>
                        <h2> Find your perfect dorm </h2>
                        <Search />
                    </div>
                </div>
            </section>
        </main>
    </div>
    )
}